container:
  image: golang:latest

env:
  GOPROXY: https://proxy.golang.org

lint_task:
  container:
    image: golangci/golangci-lint:latest
  lint_script:
    - golangci-lint run -v -p format -D goimports

test_task:
  depends_on:
    - lint
  test_script:
    - go test -v ./...

build_task:
  depends_on:
    - test
  build_script:
    - go build
