container:
  image: golang:latest

env:
  GOPROXY: https://proxy.golang.org

lint_task:
  container:
    image: golangci/golangci-lint:latest
  lint_script:
    - golangci-lint run -v -p bugs,complexity,format,performance,style,unused -D goimports,wsl,gochecknoglobals,funlen

test_task:
  depends_on:
    - lint
  env:
    CODECOV_TOKEN: ENCRYPTED[eb3a139bee16efc210790c5be7d89160ed9fd382580c0820dfd9739f5ed978406b89b4fee722f6066bf14d29a5f886ad]
  test_script:
    - go test -v -coverprofile=coverage.txt -covermode=atomic ./...
    - bash <(curl -s https://codecov.io/bash)

build_task:
  depends_on:
    - test
  build_script:
    - go build
