container:
  image: debian:latest

env:
  CIRRUS_AGENT_VERSION: 1.14.0

docker_builder:
  node_modules_cache:
    folder: "**/node_modules"
    fingerprint_script: pwd
    populate_script:
      - touch preprocessor/node_modules/cache-me.txt
  script: find .
